version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/script_bd.sql:/docker-entrypoint-initdb.d/script_bd.sql

  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mysql
  #   environment:
  #     DB_HOST: ${DB_HOST}
  #     DB_USER: ${DB_USER}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     DB_NAME: ${DB_NAME}
  #     SECRET_KEY: ${SECRET_KEY}

volumes:
  mysql-data: